SET SQL_MODE = 'ORACLE';

CREATE OR REPLACE PROCEDURE INITIALIZE_TABLES() AS 
BEGIN
	DROP TABLE REIMBURSEMENT;
	DROP TABLE EMPLOYEE;
	DROP TABLE MANAGER;
	CREATE TABLE MANAGER(
	MANAGER_ID INT(200) PRIMARY KEY AUTO_INCREMENT,
	FIRST_NAME VARCHAR(200) NOT NULL,
	LAST_NAME VARCHAR(200) NOT NULL,
	DIVISION VARCHAR(200) NOT NULL,
	USERNAME VARCHAR(200) UNIQUE NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL,
	CONSTRAINT UC_FULL_NAME UNIQUE (FIRST_NAME, LAST_NAME)
	);

	CREATE TABLE EMPLOYEE(
	EMPLOYEE_ID INT(200) PRIMARY KEY AUTO_INCREMENT,
	FIRST_NAME VARCHAR(200) NOT NULL,
	LAST_NAME VARCHAR(200) NOT NULL,
	BALANCE INT(200) NOT NULL CHECK (BALANCE >= 0),
	USERNAME VARCHAR(200) UNIQUE NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL,
	MANAGER_ID INT(200) NOT NULL,
	CONSTRAINT UC_FULL_NAME UNIQUE (FIRST_NAME, LAST_NAME),
	CONSTRAINT FK_EMPLOYEE_MANAGER FOREIGN KEY EMPLOYEE(MANAGER_ID) REFERENCES MANAGER(MANAGER_ID)
	);

	CREATE TABLE REIMBURSEMENT(
	REIMBURSEMENT_ID INT(200) PRIMARY KEY AUTO_INCREMENT,
	AMOUNT_REQUESTED INT(200) NOT NULL CHECK (AMOUNT_REQUESTED > 0),
	STATUS VARCHAR(200) NOT NULL,
	CATEGORY VARCHAR(200) NOT NULL,
	AMOUNT_PAID INT(200),
	EMPLOYEE_ID INT(200) NOT NULL,
	CONSTRAINT FK_REIMBURSEMENT_EMPLOYEE FOREIGN KEY REIMBURSEMENT(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
	);
END;

CALL INITIALIZE_TABLES();

SELECT * FROM MANAGER;
SELECT * FROM EMPLOYEE;
SELECT * FROM REIMBURSEMENT;
INSERT INTO MANAGER VALUES (0, 'John', 'Jackson', 'Weapons', 'JohnnyGunner', 'password');
INSERT INTO EMPLOYEE VALUES(0, 'Mohammed', 'Ahmed', '0', 'rizhall', '1234', 1);
INSERT INTO REIMBURSEMENT VALUES(0, 200, 'PENDING', 'EQUIPMENT',0,1);